import {StyleSheet} from 'react-native';
import {hp, wp} from '../../../util/index';

const createStyles = theme => {
  const styles = StyleSheet.create({
    mainContainer: {
      flex: 1,
      backgroundColor: theme.color.textWhite,
      flexGrow: 1,
    },
    inputContainer: {
      flexGrow: 1,
      marginTop: hp(3),
      marginHorizontal: wp(4),
    },
    headerText: {
      fontSize: theme.size.large,
      color: theme.color.textBlack,
      fontFamily: theme.fontFamily.fontFamilySoraExtraBold,
      textAlign: 'left',
      paddingHorizontal: wp(7),
      marginTop: hp(5),
    },
    headerContainerStyle: {
      borderBottomColor: theme.color.textWhite,
      backgroundColor: theme.color.textWhite,
    },
    headerColor: theme.color.textWhite,
    statusBar: {
      backgroundColor: 'white',
    },
    inputContainerStyleWithRed: {
      borderColor: theme.color.textRed,
      borderRadius: theme.borders.radius1,
      alignItems: 'center',
      borderWidth: wp(0.2),
      backgroundColor: theme.color.textWhite,
      borderBottomWidth: wp(0.2),
      paddingHorizontal: wp(4),
      height: hp(6),
    },
    inputContainerStyleWithBlack: {
      borderColor: theme.color.textBlack,
      borderRadius: theme.borders.radius1,
      alignItems: 'center',
      borderWidth: wp(0.2),
      backgroundColor: theme.color.textWhite,
      borderBottomWidth: wp(0.2),
      paddingHorizontal: wp(4),
      height: hp(6),
    },
    inputContainerStyleWithGreen: {
      borderColor: theme.color.textFieldGreen,
      borderRadius: theme.borders.radius1,
      alignItems: 'center',
      borderWidth: wp(0.2),
      backgroundColor: theme.color.textWhite,
      borderBottomWidth: wp(0.2),
      paddingHorizontal: wp(4),
      height: hp(6),
    },
    inputContainerStyle: {
      borderColor: theme.color.inputTitleColor,
      borderRadius: theme.borders.radius1,
      alignItems: 'center',
      borderWidth: wp(0.2),
      backgroundColor: theme.color.textWhite,
      borderBottomWidth: wp(0.2),
      paddingHorizontal: wp(4),
      height: hp(6),
    },

    inputStyle: {
      backgroundColor: 'transparent',
      borderWidth: wp(0),
      height: hp(3),
      borderBottomWidth: wp(0),
      overflow: 'hidden',
    },
    container: {
      flexGrow: 1,
      marginTop: hp(0.1),
      paddingHorizontal: wp(2),
      paddingBottom: hp(5),
      backgroundColor: theme.color.textWhite,
      justifyContent: 'space-between',
    },
    loginText: {
      fontSize: hp(3.5),
      fontFamily: theme.fontFamily.boldFamily,
      paddingVertical: hp(2),
      alignSelf: 'center',
    },
    textFieldTitle: {
      fontSize: theme.size.xSmall,
      textAlign: 'left',
      paddingLeft: wp(3.5),
      marginBottom: hp(0.5),
      fontFamily: theme.fontFamily.fontFamilySoraBold,
      color: theme.color.titleColor,
    },
    loginInputText: {
      fontSize: theme.size.xSmall,
      fontFamily: theme.fontFamily.fontFamilySoraRegular,
    },
    headerImage: {
      height: hp(10),
    },
    loggingText: {
      fontSize: theme.size.small,
      color: theme.color.textBlack,
      fontFamily: theme.fontFamily.fontFamilySoraSemiBold,
      textDecorationLine: 'underline',
      paddingTop: hp(3),
    },
    ErrorContainer: {
      flexDirection: 'row',
      alignItems: 'center',
      marginHorizontal: wp(3),
      marginTop: -hp(2),
      marginBottom: hp(1),
    },
    loginButton: {
      width: wp(82),
      height: hp(7),
      borderRadius: theme.borders.radius1,
      alignSelf: 'center',
      justifyContent: 'center',
      alignItems: 'center',
      marginTop: hp(5),
      borderWidth: hp(0.01),
      borderColor: theme.color.textWhite,
      fontFamily: theme.fontFamily.fontFamilySoraSemiBold,
      backgroundColor: theme.color.buttonColor,
    },
    legalText: {
      fontSize: hp(1.8),
      color: theme.color.textBlack,
      fontFamily: theme.fontFamily.fontFamilySoraExtraBold,
      paddingBottom: hp(1),
    },
    text: {
      fontSize: theme.size.small,
      fontFamily: theme.fontFamily.fontFamilySoraBold,
      color: theme.color.textWhite,
    },
    errorTextPassword: {
      fontSize: theme.size.xSmall,
      color: theme.color.textRed,
      marginHorizontal: wp(4),
      marginTop: hp(1),
    },
    img: {
      width: wp(5),
      height: hp(4),
    },
    errorText: {
      fontSize: theme.size.xSmall,
      color: theme.color.textBlack,
      fontFamily: theme.fontFamily.fontFamilySoraRegular,

      marginHorizontal: wp(1),
    },
    inputSubContainer: {
      width: wp(73),
      height: hp(7),
      overflow: 'hidden',
    },
    resetPasswordContainer: {
      marginTop: hp(25),
      paddingHorizontal: wp(3),
    },
    forgotPasswordText: {
      fontSize: theme.size.small,
      paddingLeft: wp(1.5),
      color: theme.color.textBlack,
      fontFamily: theme.fontFamily.fontFamilySoraSemiBold,
      marginBottom: hp(1.5),
      marginRight: wp(1),
      textDecorationLine: 'underline',
    },

    headerTextTermModal: {
      fontSize: theme.size.small,
      color: theme.color.textBlack,
      fontFamily: theme.fontFamily.fontFamilySoraBold,
      textAlign: 'center',
      marginVertical: hp(2),
      width: wp(65),
      marginTop: -hp(0.2),
    },

    headerTextModal: {
      fontSize: theme.size.small,
      color: theme.color.textBlack,
      fontFamily: theme.fontFamily.fontFamilySoraBold,
      textAlign: 'center',
      marginVertical: hp(2),
      width: wp(65),
      marginTop: -hp(1.5),
    },
    headerSubTextModal: {
      fontSize: hp(1.6),
      color: theme.color.textBlack,
      textAlign: 'center',
      paddingTop: hp(0.3),
      fontFamily: theme.fontFamily.fontFamilySoraRegular,
      width: wp(65),
    },
    iconContainer: {
      width: wp(5),
      height: hp(4),
      justifyContent: 'flex-start',
      borderRadius: hp(1),
      alignItems: 'center',
      zIndex: 10,
    },
    dialogStyle: {height: hp(100), alignSelf: 'center', width: wp(100)},
    codeText: {
      fontSize: theme.size.xSmall,
      color: theme.color.textBlack,
      alignSelf: 'center',
      textAlign: 'center',
    },
    headerImage: {
      height: hp(21),
    },
    codeTextContainer: {
      flexDirection: 'row',
      marginTop: hp(3),
      alignSelf: 'flex-end',
      alignItems: 'center',
      justifyContent: 'center',
      paddingRight: wp(2),
    },
    optContainer: {
      flexGrow: 1,
      alignSelf: 'center',
      justifyContent: 'center',
      alignItems: 'center',
      marginTop: hp(5),
      height: hp(30),
    },
    resendText: {
      fontSize: theme.size.small,
      fontFamily: theme.fontFamily.semiBoldFamily,
      color: theme.color.textBlack,
    },
  });
  return styles;
};
export default createStyles;
