import {StyleSheet} from 'react-native';
import {hp, wp} from '../../../util/index';

const createStyles = theme => {
  const styles = StyleSheet.create({
    mainContainer: {
      backgroundColor: theme.color.textWhite,
      flexGrow: 1,
    },

    headerText: {
      fontSize: theme.size.medium,
      color: theme.color.textWhite,
      fontFamily: theme.fontFamily.semiBoldFamily,
      marginLeft: wp(2),
    },

    headerContainerStyle: {
      borderBottomColor: theme.color.textWhite,
      backgroundColor: theme.color.textWhite,
    },
    headerColor: theme.color.textWhite,
    statusBar: {
      backgroundColor: 'white',
    },
    headerLogoImage: {width: wp(10), height: hp(7), marginTop: hp(2)},

    headerImage: {
      height: hp(10),
    },
    iconContainer: {
      width: wp(5),
      height: hp(4),
      justifyContent: 'flex-start',
      borderRadius: hp(1),
      alignItems: 'center',
      zIndex: 10,
    },
    errorText: {
      fontSize: theme.size.small,
      color: theme.color.textBlack,
      fontFamily: theme.fontFamily.semiBoldFamily,
      textAlign: 'center',
      margin: wp(5),
      // marginLeft: wp(2),
    },
    holdingText: {
      fontSize: theme.size.small,
      fontFamily: theme.fontFamily.fontFamilySoraSemiBold,
      color: theme.color.textBlack,
      paddingHorizontal: wp(3),
      marginTop: hp(2),
    },
    container: {
      paddingHorizontal: wp(2),
      paddingRight: wp(2),
      marginTop: hp(1),
      paddingBottom: hp(30),
      backgroundColor: theme.color.textWhite,
    },

    descriptionText: {
      fontSize: theme.size.xSmall,
      fontFamily: theme.fontFamily.fontFamilySoraRegular,
      color: theme.color.textBlack,
      paddingHorizontal: wp(2),
      paddingBottom: hp(2),
    },
    portfolioChartStyle: {
      alignSelf: 'center',
    },

    text: {
      fontSize: theme.size.xSmall,
      fontFamily: theme.fontFamily.fontFamilySoraBold,
      color: theme.color.textWhite,
      textAlign: 'center',
    },
    valueText: {
      fontSize: theme.size.small,
      fontFamily: theme.fontFamily.fontFamilySoraBold,
      color: theme.color.textWhite,
      textAlign: 'center',
    },
    nameText: {
      fontSize: theme.size.xSmall,
      fontFamily: theme.fontFamily.fontFamilySoraBold,
      color: theme.color.textWhite,
      textAlign: 'center',
      width: wp(30),
    },
    nameTextImpact: {
      fontSize: theme.size.xSmall,
      fontFamily: theme.fontFamily.fontFamilySoraBold,
      color: theme.color.textWhite,
      textAlign: 'center',
      width: wp(70),
      marginTop: hp(2),
    },
    nameTextBroadText: {
      fontSize: theme.size.xSmall,
      fontFamily: theme.fontFamily.fontFamilySoraBold,
      color: theme.color.textWhite,
      textAlign: 'center',
      width: wp(60),
    },
    carbonButton: {
      height: hp(4),
      padding: wp(1),
      paddingHorizontal: wp(8),
      borderRadius: theme.borders.radius4,
      alignSelf: 'center',
      justifyContent: 'center',
      alignItems: 'center',
      borderWidth: hp(0.01),
      borderColor: theme.color.textWhite,
      backgroundColor: theme.color.textBlack,
    },
    readImpactButton: {
      height: hp(4),
      paddingHorizontal: wp(6),
      borderRadius: theme.borders.radius4,
      alignSelf: 'center',
      justifyContent: 'center',
      alignItems: 'center',
      borderWidth: hp(0.01),
      borderColor: theme.color.textWhite,
      backgroundColor: theme.color.textBlack,
      marginBottom: hp(4),
    },
    imageBackgroundStyle: {
      // justifyContent: 'center',
      borderWidth: wp(0.2),
      borderColor: theme.color.textRed,
      margin: wp(1),

      borderRadius: theme.borders.radius1,
    },

    flatContainerImg: {
      width: wp(45),
      height: hp(20),
      borderColor: 'black',
      borderWidth: wp(0.01),
      overflow: 'hidden',
      borderRadius: hp(1.5),
    },
    GridViewContainer: {
      margin: wp(1),
      backgroundColor: theme.color.textBlack,
    },
    barChartFont: {fontFamily: theme.fontFamilySoraSemiBold},
    flatContainer: {
      overflow: 'hidden',
      flexWrap: 'wrap',
      flex: 1,
      margin: wp(0.7),
      backgroundColor: theme.color.textBlack,
      borderRadius: hp(1),
    },
    row: {
      flexWrap: 'wrap',
      flex: 1,
    },
    emptyListStyle: {justifyContent: 'center', alignItems: 'center', flex: 1},
    imgBackgroundStyle: {
      position: 'absolute',
      margin: wp(0.5),
      marginLeft: -wp(2),
      top: 0,
      left: 0,
      right: 0,
      bottom: 0,
      borderRadius: hp(0.8),
      borderWidth: wp(0.01),
      borderColor: 'black',
      justifyContent: 'space-between',
      alignItems: 'center',
      alignSelf: 'center',
      overflow: 'hidden',
    },
    headerContainerStyleHelp: {
      borderBottomColor: theme.color.textWhite,
      backgroundColor: theme.color.textWhite,
    },
    modalImg: {width: wp(40), height: wp(40), alignSelf: 'center'},
    modalImgImpact: {width: wp(100), height: wp(50), alignSelf: 'center'},

    modalSuText: {
      fontSize: theme.size.xSmall,
      color: theme.color.textBlack,
      fontFamily: theme.fontFamily.fontFamilySoraRegular,
      textAlign: 'left',
      marginBottom: hp(2),
      lineHeight: hp(3),
    },
    modalSubText: {
      fontSize: hp(1.8),
      color: theme.color.textBlack,
      fontFamily: theme.fontFamily.fontFamilySoraRegular,
      textAlign: 'left',
      marginTop: hp(2),
      lineHeight: hp(3.5),
    },
    modalSubTextWithoutTopMargin: {
      fontSize: hp(1.8),
      color: theme.color.textBlack,
      fontFamily: theme.fontFamily.fontFamilySoraRegular,
      textAlign: 'left',
      marginTop: -hp(3.5),
      lineHeight: hp(3.5),
      marginBottom: hp(2),
    },
    modalContainer: {
      marginTop: hp(1),
      paddingBottom: hp(10),
      paddingHorizontal: wp(6),
      backgroundColor: theme.color.textWhite,
      justifyContent: 'space-between',
    },
    boldTextModal: {
      fontSize: hp(1.8),
      color: theme.color.textBlack,
      marginBottom: hp(1),
      fontFamily: theme.fontFamily.fontFamilySoraBold,
    },
    title: {
      fontSize: theme.size.large,
      fontFamily: theme.fontFamily.fontFamilySoraBold,
      textAlign: 'center',
    },
    headerTextModal: {
      fontSize: theme.size.small,
      color: theme.color.textBlack,
      fontFamily: theme.fontFamily.fontFamilySoraBold,
      textAlign: 'center',
      marginVertical: hp(2),
      width: wp(65),
      marginTop: -hp(0.2),
    },
    headerTextImpactModal: {
      fontSize: hp(3),
      color: theme.color.textBlack,
      fontFamily: theme.fontFamily.fontFamilySoraSemiBold,
      textAlign: 'center',
      marginVertical: hp(2),
      width: wp(80),
      marginTop: -hp(0.2),
    },
    initialTextModal: {
      fontFamily: theme.fontFamily.fontFamilyLoraItalic,
      textAlign: 'left',
      fontSize: hp(7),
      color: theme.color.buttonColor,
      borderTopColor: theme.color.textBlack,
      marginVertical: hp(3),
      lineHeight: hp(7),
    },
    dateModalText: {
      fontFamily: theme.fontFamily.fontFamilyLoraItalic,
      textAlign: 'center',
      fontSize: theme.size.xSmall,
      color: theme.color.textBlack,
      borderTopColor: theme.color.textBlack,
      alignSelf: 'center',
      // fontStyle:'italic',
      paddingTop: hp(1),
    },
    lineStyle: {
      textAlign: 'center',
      borderTopWidth: wp(0.5),
      fontSize: theme.size.small,
      color: theme.color.textBlack,
      alignSelf: 'center',
      width: wp(20),
    },
    modalSuTextFontBold: {
      fontSize: theme.size.xSmall,
      color: theme.color.textBlack,
      fontFamily: theme.fontFamily.fontFamilySoraSemiBold,
      textAlign: 'left',
      marginBottom: hp(2),
      lineHeight: hp(3),
    },
  });
  return styles;
};
export default createStyles;
