import {StyleSheet} from 'react-native';
import {hp, wp} from '../../../util/index';

const createStyles = theme => {
  const styles = StyleSheet.create({
    mainContainer: {
      flex: 1,
      backgroundColor: theme.color.textWhite,
      flexGrow: 1,
      paddingLeft: wp(3),
    },
    inputContainer: {
      flexGrow: 1,
      marginTop: hp(3),
    },
    headerText: {
      fontSize: theme.size.medium,
      color: theme.color.textBlack,
      fontFamily: theme.fontFamily.boldFamily,
      textAlign: 'left',
      marginVertical: hp(1),
    },
    amountText: {
      fontSize: theme.size.xLarge,
      color: theme.color.textBlack,
      fontFamily: theme.fontFamily.fontFamilySoraBold,
      textAlign: 'center',
    },
    shareText: {
      fontSize: theme.size.large,
      color: theme.color.textBlack,
      fontFamily: theme.fontFamily.fontFamilySoraBold,
      textAlign: 'center',
      marginTop: hp(3),
    },
    headerContainerStyle: {
      borderBottomColor: theme.color.textWhite,
      backgroundColor: theme.color.textWhite,
    },
    headerColor: theme.color.textWhite,
    statusBar: {
      backgroundColor: 'transparent',
    },

    container: {
      flexGrow: 1,
      marginTop: hp(2),
      paddingBottom: hp(13),
      backgroundColor: theme.color.textWhite,
      justifyContent: 'space-between',
    },
    feedbackContainer: {
      flexGrow: 1,
      marginTop: hp(2),
      paddingBottom: hp(13),
      // marginHorizontal:wp(3),
      backgroundColor: theme.color.textWhite,
      justifyContent: 'space-between',
    },
    feedbackContainer: {
      flexGrow: 1,
      marginTop: hp(2),
      paddingHorizontal: wp(2),
      paddingBottom: hp(13),
      backgroundColor: theme.color.textWhite,
      justifyContent: 'center',
      alignItems: 'center',
    },
    viewAccountButton: {
      width: wp(50),
      height: hp(6),
      borderRadius: theme.borders.radius1,
      alignSelf: 'center',
      justifyContent: 'center',
      marginBottom: hp(7),
      // position:'absolute',
      // bottom:0,
      alignItems: 'center',
      borderWidth: hp(0.01),
      borderColor: theme.color.textWhite,
      backgroundColor: theme.color.textBlack,
    },
    submitFeedbackButton: {
      width: wp(85),
      height: hp(7),
      borderRadius: theme.borders.radius1,
      alignSelf: 'center',
      justifyContent: 'center',
      marginBottom: hp(4),
      alignItems: 'center',
      borderWidth: hp(0.01),
      borderColor: theme.color.textWhite,
      backgroundColor: theme.color.textBlack,
    },
    versionText: {
      fontSize: theme.size.xSmall,
      fontFamily: theme.fontFamily.semiBoldFamily,
      color: '#8F90A6',
      paddingLeft: wp(4),
      marginTop: -hp(2.5),
    },
    FeedbackSubmitText: {
      fontSize: theme.size.large,
      fontFamily: theme.fontFamily.fontFamilySoraBold,
      color: theme.color.textBlack,
      textAlign: 'center',
    },
    thankText: {
      fontSize: theme.size.medium,
      fontFamily: theme.fontFamily.fontFamilySoraRegular,
      color: theme.color.textBlack,
      textAlign: 'center',
      marginVertical: hp(5),
    },
    headerModalText: {
      fontSize: theme.size.small,
      fontFamily: theme.fontFamily.semiBoldFamily,
      color: theme.color.textBlack,
    },
    textFieldTitle: {
      fontSize: theme.size.xSmall,
      textAlign: 'left',
      paddingLeft: wp(3.5),
      marginBottom: hp(0.5),
      fontFamily: theme.fontFamily.fontFamilySoraBold,
      color: theme.color.titleColor,
    },
    containerStyle: {
      height: null,
      maxHeight: hp(70),
    },
    loginInputText: {
      fontSize: theme.size.xSmall,
      fontFamily: theme.fontFamily.fontFamilySoraRegular,
      height: null,
      maxHeight: hp(70),
      textAlignVertical: 'top',
    },
    inputContainerStyleWithRed: {
      borderColor: theme.color.textRed,
      borderRadius: theme.borders.radius1,
      alignItems: 'flex-start',
      borderWidth: wp(0.2),
      backgroundColor: theme.color.textWhite,
      borderBottomWidth: wp(0.2),
      paddingHorizontal: wp(4),
      height: null,
      maxHeight: hp(70),
    },
    inputContainerStyleWithBlack: {
      borderColor: theme.color.textBlack,
      borderRadius: theme.borders.radius1,
      alignItems: 'flex-start',
      borderWidth: wp(0.2),
      backgroundColor: theme.color.textWhite,
      borderBottomWidth: wp(0.2),
      paddingHorizontal: wp(4),
      height: null,
      maxHeight: hp(70),
    },
    inputContainerStyleWithGreen: {
      borderColor: theme.color.textFieldGreen,
      borderRadius: theme.borders.radius1,
      alignItems: 'flex-start',
      borderWidth: wp(0.2),
      backgroundColor: theme.color.textWhite,
      borderBottomWidth: wp(0.2),
      paddingHorizontal: wp(4),
      height: null,
      maxHeight: hp(70),
    },
    inputContainerStyle: {
      borderColor: theme.color.inputTitleColor,
      borderRadius: theme.borders.radius1,
      alignItems: 'flex-start',
      borderWidth: wp(0.2),
      backgroundColor: theme.color.textWhite,
      borderBottomWidth: wp(0.2),
      paddingHorizontal: wp(4),
      height: null,
      maxHeight: hp(70),
    },
    errorText: {
      fontSize: theme.size.xSmall,
      color: theme.color.textBlack,
      fontFamily: theme.fontFamily.fontFamilySoraRegular,
      marginHorizontal: wp(1),
    },
    ErrorContainer: {
      flexDirection: 'row',
      alignItems: 'center',
      marginHorizontal: wp(3),
      marginTop: hp(7),
    },
    headerSubText: {
      fontSize: theme.size.xSmall,
      color: theme.color.textBlack,
      alignSelf: 'center',
      marginTop: -hp(1.5),
      width: wp(55),
      textAlign: 'center',
    },
    iconContainer: {
      width: hp(4),
      height: hp(4),
      justifyContent: 'center',
      alignItems: 'center',
    },

    headerImage: {
      height: hp(13),
    },

    text: {
      fontSize: theme.size.xSmall,
      fontFamily: theme.fontFamily.fontFamilySoraBold,
      color: theme.color.textWhite,
    },
    titleContainer: {
      justifyContent: 'space-between',
      width: wp(55),
      marginTop: hp(7),
    },
    subText: {
      fontFamily: theme.fontFamily.fontFamilySoraSemiBold,
      color: theme.color.textBlack,
      width: wp(85),
    },
    ProfileTitle: {
      fontSize: hp(1.7),
      fontFamily: theme.fontFamily.fontFamilySoraSemiBold,
      color: theme.color.fadeTitle,
    },
    ProfileSubText: {
      fontSize: theme.size.xSmall,
      fontFamily: theme.fontFamily.fontFamilySoraRegular,
      color: theme.color.fadeSubTitle,
    },
    comingSoonText: {
      fontFamily: theme.fontFamily.fontFamilySoraBold,
      color: theme.color.textBlack,
      fontSize: hp(2.1),
    },
    comingSoonContainer: {
      marginLeft: wp(4),
      marginVertical: hp(2),
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
    },
    divider: {
      width: wp(90),
      backgroundColor: '#E4E4EB',
      marginLeft: wp(4),
      height: hp(0.2),
      marginTop: hp(0.5),
    },
    feedbackIcon: {
      width: wp(5),
      height: wp(5),
    },
    img: {
      width: wp(7),
      height: wp(7),
    },
    countText: {
      fontSize: theme.size.xSmall,
      fontFamily: theme.fontFamily.fontFamilySoraBold,
      color: theme.color.textWhite,
    },
    title: {
      fontSize: theme.size.small,
      fontFamily: theme.fontFamily.fontFamilySoraBold,
      color: theme.color.textBlack,
      flexDirection: 'row',
      marginBottom: hp(1),
    },
    notificationsCount: {
      width: wp(7),
      height: wp(7),
      borderRadius: hp(7),
      backgroundColor: theme.color.textBlack,
      justifyContent: 'center',
      alignItems: 'center',
    },
    accountProgressContainer: {
      flexGrow: 1,
      backgroundColor: theme.color.accountColor,
      marginHorizontal: wp(4),
      paddingVertical: hp(2),
    },
  });
  return styles;
};
export default createStyles;
