import {StyleSheet} from 'react-native';
import {hp, wp} from '../../../util/index';

const createStyles = theme => {
  const styles = StyleSheet.create({
    mainContainer: {
      backgroundColor: theme.color.textWhite,
      flexGrow: 1,
    },

    headerText: {
      fontSize: theme.size.medium,
      color: theme.color.textBlack,
      fontFamily: theme.fontFamily.semiBoldFamily,
      marginLeft: wp(2),
      width: wp(70),
    },
    inputContainerStyle: {
      borderColor: theme.color.textWhite,
      alignItems: 'center',
      backgroundColor: theme.color.textWhite,
      // marginHorizontal: wp(30),
      // margin:hp(10),
      height: hp(10),
    },
    errorText: {
      textAlign: 'center',
      fontSize: theme.size.xSmall,
      color: theme.color.textRed,
      marginHorizontal: wp(3),
    },
    loginInputText: {
      fontSize: theme.size.xLarge,
      color: theme.color.textBlack,
      fontFamily: theme.fontFamily.fontFamilySoraBold,
      textAlign: 'center',
    },
    inputContainer: {
      flexGrow: 1,
      marginTop: hp(3),
    },
    homeText: {
      fontSize: theme.size.medium,
      color: theme.color.textBlack,
      fontFamily: theme.fontFamily.semiBoldFamily,
      textAlign: 'center',
    },
    lineGraphTitle: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      paddingHorizontal: wp(2),
      paddingRight: wp(4),
    },
    headerContainerStyleHelp: {
      borderBottomColor: theme.color.textWhite,
      backgroundColor: theme.color.textWhite,
    },
    cardStyle: {
      flexGrow: 1,
      width: wp(92),
      alignSelf: 'center',
      backgroundColor: theme.color.textWhite,
      borderColor: theme.color.textWhite,
    },
    headerStyle: {paddingVertical: hp(0)},

    headerContainerStyle: {
      borderBottomColor: theme.color.textWhite,
      backgroundColor: theme.color.textWhite,
    },
    headerColor: theme.color.textWhite,
    statusBar: {
      backgroundColor: 'white',
    },
    questionMarkImg: {width: wp(6), height: wp(6)},
    activityStyle: {marginTop: hp(5), alignSelf: 'center'},
    graphTitle: {
      fontSize: theme.size.large,
      fontFamily: theme.fontFamily.fontFamilySoraBold,
      color: theme.color.textGreen,
      textAlign: 'left',
      marginTop: -hp(1),
      marginHorizontal: wp(5),
    },
    headerLogoImage: {width: wp(10), height: hp(7), marginTop: hp(2)},

    headerImage: {
      height: hp(10),
    },
    overviewText: {
      fontSize: theme.size.medium,
      fontFamily: theme.fontFamily.fontFamilySoraBold,
      color: theme.color.textBlack,
      textAlign: 'left',
      paddingHorizontal: wp(3.5),
      marginTop: hp(2),
    },
    holdingsText: {
      fontSize: theme.size.medium,
      fontFamily: theme.fontFamily.fontFamilySoraBold,
      color: theme.color.textBlack,
      textAlign: 'left',
      paddingVertical: hp(2),
      paddingHorizontal: wp(4.5),
    },
    ecoFundText: {
      fontSize: hp(2.3),
      fontFamily: theme.fontFamily.fontFamilySoraRegular,
      color: theme.color.textBlack,
      textAlign: 'left',
      paddingVertical: hp(1.5),
      paddingHorizontal: wp(4),
    },
    faqTitle: {
      fontSize: hp(1.8),
      fontFamily: theme.fontFamily.fontFamilySoraRegular,
      color: theme.color.textBlack,
      textAlign: 'left',
      paddingVertical: hp(2),
      paddingLeft: wp(3),
      width: wp(70),
    },
    counterImageStyle: {
      fontFamily: theme.fontFamily.fontFamilySoraBold,
      textAlign: 'center',
      zIndex: 14,
      color: theme.color.textWhite,
      position: 'absolute',
      alignSelf: 'center',
      marginTop: hp(2),
      fontSize: theme.size.medium,
    },
    errorText: {
      fontSize: theme.size.small,
      color: theme.color.textBlack,
      fontFamily: theme.fontFamily.semiBoldFamily,
      textAlign: 'center',
      margin: wp(5),
      // marginLeft: wp(2),
    },
    counterSubImageStyle: {
      fontFamily: theme.fontFamily.fontFamilySoraBold,
      textAlign: 'center',
      zIndex: 14,
      color: theme.color.textWhite,
      position: 'absolute',
      fontSize: theme.size.small,
    },
    overlay: {
      backgroundColor: theme.color.textBlack,
      justifyContent: 'center',
      alignItems: 'center',
      borderRadius: theme.borders.radius1,
      width: wp(26),
      height: wp(26),
    },
    container: {
      backgroundColor: theme.color.textWhite,
      justifyContent: 'space-between',
    },
    investModalContainer: {
      flexGrow: 1,
      marginTop: hp(1),
      backgroundColor: theme.color.textWhite,
      justifyContent: 'space-between',
    },
    modalContainer: {
      marginTop: hp(1),
      paddingBottom: hp(10),
      paddingHorizontal: wp(6),
      backgroundColor: theme.color.textWhite,
      justifyContent: 'space-between',
    },
    inputContainerStyleWithRed: {
      borderColor: theme.color.textWhite,
      borderRadius: theme.borders.radius1,
      alignItems: 'center',
      borderWidth: wp(0.2),
      backgroundColor: theme.color.textWhite,
      borderBottomWidth: wp(0.2),
      paddingHorizontal: wp(4),
      height: hp(6),
    },
    inputContainerStyleWithBlack: {
      borderColor: theme.color.textWhite,
      borderRadius: theme.borders.radius1,
      alignItems: 'center',
      borderWidth: wp(0.2),
      backgroundColor: theme.color.textWhite,
      borderBottomWidth: wp(0.2),
      paddingHorizontal: wp(4),
      height: hp(6),
    },
    inputContainerStyleWithGreen: {
      borderColor: theme.color.textWhite,
      borderRadius: theme.borders.radius1,
      alignItems: 'center',
      borderWidth: wp(0.2),
      backgroundColor: theme.color.textWhite,
      borderBottomWidth: wp(0.2),
      paddingHorizontal: wp(4),
      height: hp(6),
    },

    graphSubText: {
      fontFamily: theme.fontFamily.fontFamilySoraSemiBold,
      color: '#A4A4A9',
      textAlign: 'left',
      width: wp(55),
      marginHorizontal: wp(5),
    },
    renderImages: {
      width: wp(25),
      height: wp(25),
      resizeMode: 'cover',
      margin: 4,
      borderRadius: theme.borders.radius1,
    },
    renderImagesOverLay: {
      width: wp(25),
      height: wp(25),
      resizeMode: 'cover',
      margin: 4,
      opacity: 0.5,
      borderRadius: theme.borders.radius1,
    },

    descriptionText: {
      fontSize: hp(1.8),
      fontFamily: theme.fontFamily.fontFamilySoraRegular,
      color: '#444757',
      textAlign: 'left',
      marginTop: hp(1),
      paddingHorizontal: wp(4),
    },
    historicalSubText: {
      fontSize: theme.size.xSmall,
      fontFamily: theme.fontFamily.fontFamilySoraBold,
      color: theme.color.textBlack,
      paddingHorizontal: wp(2),
    },
    portfolioChartStyle: {
      alignSelf: 'center',
    },
    investButton: {
      width: wp(92),
      height: hp(7),
      borderRadius: theme.borders.radius1,
      alignSelf: 'center',
      justifyContent: 'center',
      alignItems: 'center',
      borderWidth: hp(0.01),
      borderColor: theme.color.textWhite,
      backgroundColor: theme.color.buttonColor,
    },
    bottomContainer: {
      backgroundColor: theme.color.textWhite,
      borderTopWidth: wp(0.1),
      borderTopColor: theme.color.dividerColor,
      height: hp(17),
      width: wp(100),
      // position: 'absolute',
      paddingVertical: hp(1.6),
      marginBottom: hp(1.5),
      justifyContent: 'flex-start',
      alignItems: 'center',
    },
    text: {
      fontSize: theme.size.small,
      fontFamily: theme.fontFamily.fontFamilySoraBold,
      color: theme.color.textWhite,
    },
    emptyMessageStyle: {
      fontSize: theme.size.small,
      color: theme.color.textBlack,
      fontFamily: theme.fontFamily.semiBoldFamily,
      textAlign: 'center',
      margin: wp(5),
    },
    emptyOverviewStyle: {
      fontSize: theme.size.small,
      color: theme.color.textBlack,
      fontFamily: theme.fontFamily.semiBoldFamily,
      textAlign: 'center',
      width: wp(100),
      paddingVertical: hp(3),
    },

    taskCard: {
      // width: wp(95),
      // paddingHorizontal: wp(2),
      flexDirection: 'row', // row
      alignItems: 'center',
      borderBottomColor: 'black',
      justifyContent: 'flex-start',
      shadowColor: theme.color.textBlack,
      shadowOffset: {width: 1, height: 1},
      shadowOpacity: 0.4,
      shadowRadius: 3,
      elevation: 5,
    },

    selectedText: {
      fontSize: theme.size.medium,
      fontFamily: theme.fontFamily.fontFamilySoraBold,
      color: theme.color.textBlack,
      textAlign: 'left',
      paddingBottom: hp(1),
      marginHorizontal: wp(1),
      borderBottomWidth: hp(0.3),
      borderBottomColor: theme.color.textBlack,
    },
    UnSelectedText: {
      fontSize: theme.size.medium,
      color: '#B4BACF',
      fontFamily: theme.fontFamily.fontFamilySoraBold,
      textAlign: 'left',
      marginHorizontal: wp(1),
      marginTop: hp(0.5),
      paddingBottom: hp(0.5),
    },
    underlineText: {
      borderWidth: 1,
      width: wp(14),
    },
    faqContainer: {
      justifyContent: 'space-between',
      padding: wp(2.5),
      flexDirection: 'column',
      marginHorizontal: wp(4),
      marginBottom: hp(1),
      borderWidth: wp(0.1),
      borderRadius: hp(0.8),
      shadowColor: theme.color.dividerColor,
      shadowOffset: {
        width: hp(1),
        height: hp(1),
      },
      shadowOpacity: 0.25,
      shadowRadius: 3.84,
      elevation: 5,
      backgroundColor: theme.color.backgroundColor,
    },
    rowContainer: {
      alignItems: 'center',
      flexDirection: 'row',
      marginHorizontal: wp(4),
      justifyContent: 'space-between',
    },
    faqAns: {
      fontSize: hp(1.8),
      fontFamily: theme.fontFamily.fontFamilySoraRegular,
      color: '#444757',
      textAlign: 'left',
      paddingVertical: hp(2),
      paddingLeft: wp(6),
    },
    selectedSubText: {
      fontSize: theme.size.small,
      fontFamily: theme.fontFamily.fontFamilySoraBold,
      color: theme.color.textBlack,
      textAlign: 'left',
    },
    UnSelectedSubText: {
      fontSize: theme.size.small,
      color: theme.color.dividerColor,
    },

    selectedTab: {
      marginLeft: wp(4),
      justifyContent: 'center',
      alignItems: 'center',
    },

    iconContainer: {
      width: wp(7),
      height: wp(7),
      borderRadius: wp(7),
      borderWidth: wp(0.2),
      borderColor: 'black',
      justifyContent: 'center',
      alignItems: 'center',
    },
    emptyListStyle: {justifyContent: 'center', alignItems: 'center', flex: 1},
    boldTextModal: {
      fontSize: hp(1.8),
      color: theme.color.textBlack,
      marginBottom: hp(1),
      fontFamily: theme.fontFamily.fontFamilySoraBold,
    },
    headerTextModal: {
      fontSize: theme.size.small,
      color: theme.color.textBlack,
      fontFamily: theme.fontFamily.fontFamilySoraBold,
      textAlign: 'center',
      marginVertical: hp(2),
      width: wp(65),
      marginTop: -hp(0.2),
    },
    modalImg: {width: wp(40), height: wp(40), alignSelf: 'center'},
    modalSuText: {
      fontSize: theme.size.xSmall,
      color: theme.color.textBlack,
      fontFamily: theme.fontFamily.fontFamilySoraRegular,
      textAlign: 'left',
      marginBottom: hp(2),
      lineHeight: hp(3),
    },
    modalSuTextFontBold: {
      fontSize: theme.size.xSmall,
      color: theme.color.textBlack,
      fontFamily: theme.fontFamily.fontFamilySoraSemiBold,
      textAlign: 'left',
      marginBottom: hp(2),
      lineHeight: hp(3),
    },
    purchaseButton: {
      width: wp(91),
      height: hp(7),
      borderRadius: theme.borders.radius1,
      alignSelf: 'center',
      justifyContent: 'center',
      position: 'absolute',
      bottom: hp(5),
      alignItems: 'center',
      borderWidth: hp(0.01),
      borderColor: theme.color.textWhite,
      backgroundColor: theme.color.buttonColor,
    },
    carbonButton: {
      width: wp(85),
      padding: wp(4),
      marginTop: hp(10),
      borderRadius: theme.borders.radius4,
      alignSelf: 'center',
      justifyContent: 'center',
      alignItems: 'center',
      borderWidth: hp(0.01),
      borderColor: theme.color.textWhite,
      backgroundColor: '#E6F9F1',
    },
    carbonText: {
      fontSize: theme.size.xSmall,
      fontFamily: theme.fontFamily.fontFamilySoraRegular,
      color: '#06C270',
      textAlign: 'center',
      textAlignVertical: 'center',
    },
    shareText: {
      fontSize: theme.size.large,
      color: theme.color.textBlack,
      fontFamily: theme.fontFamily.fontFamilySoraBold,
      textAlign: 'center',
      marginTop: hp(3),
    },
    errorText: {
      textAlign: 'center',
      fontSize: theme.size.xSmall,
      color: theme.color.textRed,
      marginHorizontal: wp(3),
    },
    successButton: {
      width: wp(40),
      height: hp(7),
      marginTop: hp(3),
      borderRadius: theme.borders.radius1,
      alignSelf: 'center',
      justifyContent: 'center',
      alignItems: 'center',
      borderWidth: hp(0.01),
      borderColor: theme.color.textWhite,
      backgroundColor: theme.color.buttonColor,
      // marginBottom:hp(5)
    },
    text: {
      fontSize: theme.size.small,
      fontFamily: theme.fontFamily.fontFamilySoraBold,
      color: theme.color.textWhite,
    },
    topBar: {
      paddingTop: hp(3.7),
      flexDirection: 'row',
      backgroundColor: theme.color.textWhite,
    },
    keyboardView: {
      marginTop: hp(4),
      alignItems: 'center',
      justifyContent: 'center',
    },
    keyboardStyle: {
      alignItems: 'center',
      justifyContent: 'center',
      margin: hp(0.3),
      width: wp(20),
      height: hp(10),
      borderRadius: theme.borders.radius2,
    },
    keyboardText: {
      alignItems: 'center',
      justifyContent: 'center',
      fontSize: theme.size.large,
      fontFamily: theme.fontFamily.mediumFamily,
    },
    iconSize: wp(10),
  });
  return styles;
};
export default createStyles;
